version: "3.8"
services:
  server: 
    image: events-collector:debug
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile 
      target: debug
    ports:
      - 9999:9999
      - 40000:40000
    volumes:
      - .:/go/app
    security_opt: 
      - seccomp:unconfined
    depends_on:
      - my-postgres
  my-postgres:
    ports:
      - '5436:5432'
    restart: always
    image: postgres
    environment: 
      POSTGRES_DB: eventscollector
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh